// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64
// +build 386 amd64

package gogc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfGcEvent struct {
	StartMonotimeNs uint64
	Action          uint32
	Lang            uint32
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	UprobeRuntimeFreeStackSpans        *ebpf.ProgramSpec `ebpf:"uprobe_runtime_freeStackSpans"`
	UprobeRuntimeGcBgMarkStartWorkers  *ebpf.ProgramSpec `ebpf:"uprobe_runtime_gcBgMarkStartWorkers"`
	UprobeRuntimeStartTheWorldWithSema *ebpf.ProgramSpec `ebpf:"uprobe_runtime_start_the_world_with_sema"`
	UprobeRuntimeStopTheWorldWithSema  *ebpf.ProgramSpec `ebpf:"uprobe_runtime_stop_the_world_with_sema"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	OngoingGoGc    *ebpf.MapSpec `ebpf:"ongoing_go_gc"`
	OngoingGoStwGc *ebpf.MapSpec `ebpf:"ongoing_go_stw_gc"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	OngoingGoGc    *ebpf.Map `ebpf:"ongoing_go_gc"`
	OngoingGoStwGc *ebpf.Map `ebpf:"ongoing_go_stw_gc"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.OngoingGoGc,
		m.OngoingGoStwGc,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	UprobeRuntimeFreeStackSpans        *ebpf.Program `ebpf:"uprobe_runtime_freeStackSpans"`
	UprobeRuntimeGcBgMarkStartWorkers  *ebpf.Program `ebpf:"uprobe_runtime_gcBgMarkStartWorkers"`
	UprobeRuntimeStartTheWorldWithSema *ebpf.Program `ebpf:"uprobe_runtime_start_the_world_with_sema"`
	UprobeRuntimeStopTheWorldWithSema  *ebpf.Program `ebpf:"uprobe_runtime_stop_the_world_with_sema"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.UprobeRuntimeFreeStackSpans,
		p.UprobeRuntimeGcBgMarkStartWorkers,
		p.UprobeRuntimeStartTheWorldWithSema,
		p.UprobeRuntimeStopTheWorldWithSema,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
